apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev

---
apiVersion: v1
kind: Service
metadata:
  name: wil42
  namespace: dev
spec:
  type: ClusterIP  # Changed from NodePort (handled by k3d)
  selector:
    app: wil42
  ports:
    - port: 80     # Matches k3d's 8888:80 mapping
      targetPort: 8888

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
        - name: wil42
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
